#!/bin/sh

set -e

project_name=${COMPOSE_PROJECT_NAME:-nickelodeon}
extra_args=''

if [ "$1" = 'exec' -a $# -eq 2 ]; then
    extra_args="$* /bin/bash"
    shift 2
fi

export GROUPID=$(id -g) USERID=$(id -u)
exec docker-compose \
    --file docker/docker-compose.yml \
    --project-name $project_name \
    $extra_args \
    "$@"
