# Generated by Django 4.2.23 on 2025-07-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nickelodeon', '0008_alter_usersettings_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp3song',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
