# Generated by Django 4.2.23 on 2025-07-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nickelodeon", "0009_mp3song_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mp3song",
            name="aac",
        ),
    ]
