# Generated by Django 5.2.4 on 2025-07-31 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nickelodeon", "0010_remove_mp3song_aac"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mp3song",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="mp3song",
            constraint=models.UniqueConstraint(
                fields=("owner", "filename"), name="unique_owner_filename"
            ),
        ),
    ]
